# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_auto_20170526_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('note', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='dairy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.User_info'),
        ),
    ]
